# Generated by Django 4.2.5 on 2023-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='creado_por',
            field=models.CharField(default='Anónimo', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='top_secret',
            field=models.CharField(default='No deberías ver esto desde el API', max_length=255),
        ),
    ]
